version: '1.0.0'
services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: fintech_application
      # So you don't have to use root, but you can if you like
      MYSQL_USER: ivan
      # You can use whatever password you like
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - "3308:3306"
      # Where our data will be persisted
    volumes:
      - my-db:/var/lib/mysql
# Names our volume
volumes:
  my-db: